export const STORE_SEGMENTS = [
  { value: "moda-calcados-acessorios", label: "Moda, Calçados e Acessórios" },
  { value: "bebidas-adegas-conveniencia", label: "Bebidas, Adega e Conveniência" },
  { value: "padaria-confeitaria-doces", label: "Padaria, Confeitaria e Doces" },
  { value: "beleza-estetica", label: "Beleza e Estética" },
  { value: "petshop", label: "Pet Shop" },
  { value: "variedades-utilidades", label: "Variedades e Utilidades" },
  { value: "mercados-mercearias", label: "Mercados e Mercearias" },
  { value: "restaurantes-lanchonetes", label: "Restaurantes e Lanchonetes" },
  { value: "farmacia-saude", label: "Farmácia e Saúde" },
  { value: "casa-decoracao", label: "Casa e Decoração" },
  { value: "eletronicos-tecnologia", label: "Eletrônicos e Tecnologia" },
  { value: "servicos-locais", label: "Serviços Locais" },
  { value: "outros", label: "Outros" },
] as const;

export type StoreSegment = (typeof STORE_SEGMENTS)[number]["value"];

export const STORE_SUBSEGMENTS: Record<StoreSegment, readonly { value: string; label: string }[]> = {
  "moda-calcados-acessorios": [
    { value: "moda-feminina", label: "Moda Feminina" },
    { value: "moda-masculina", label: "Moda Masculina" },
    { value: "moda-infantil", label: "Moda Infantil" },
    { value: "calcados-femininos", label: "Calçados Femininos" },
    { value: "calcados-masculinos", label: "Calçados Masculinos" },
    { value: "calcados-infantis", label: "Calçados Infantis" },
    { value: "acessorios", label: "Acessórios" },
    { value: "bolsas-mochilas", label: "Bolsas e Mochilas" },
    { value: "joias-bijuterias", label: "Joias e Bijuterias" },
    { value: "roupas-intimas", label: "Roupas Íntimas" },
    { value: "moda-praia", label: "Moda Praia" },
    { value: "outro", label: "Outro" },
  ] as const,
  "bebidas-adegas-conveniencia": [
    { value: "cervejas-especiais", label: "Cervejas Especiais" },
    { value: "vinhos", label: "Vinhos" },
    { value: "destilados", label: "Destilados" },
    { value: "refrigerantes", label: "Refrigerantes" },
    { value: "sucos", label: "Sucos" },
    { value: "aguas", label: "Águas" },
    { value: "energeticos", label: "Energéticos" },
    { value: "conveniencia-alimentacao", label: "Conveniência e Alimentação" },
    { value: "gelo-e-gelados", label: "Gelo e Gelados" },
    { value: "outro", label: "Outro" },
  ] as const,
  "padaria-confeitaria-doces": [
    { value: "paes-artesanais", label: "Pães Artesanais" },
    { value: "bolos-tortas", label: "Bolos e Tortas" },
    { value: "doces-caseiros", label: "Doces Caseiros" },
    { value: "salgados-assados", label: "Salgados Assados" },
    { value: "confeitaria-fina", label: "Confeitaria Fina" },
    { value: "salgados-fritos", label: "Salgados Fritos" },
    { value: "cafeteria", label: "Cafeteria" },
    { value: "sucos-naturais", label: "Sucos Naturais" },
    { value: "sorvetes-acai", label: "Sorvetes e Açaí" },
    { value: "outro", label: "Outro" },
  ] as const,
  "beleza-estetica": [
    { value: "cabeleireiro", label: "Cabeleireiro" },
    { value: "barbearia", label: "Barbearia" },
    { value: "manicure-pedicure", label: "Manicure e Pedicure" },
    { value: "estetica-facial", label: "Estética Facial" },
    { value: "estetica-corporal", label: "Estética Corporal" },
    { value: "maquiagem", label: "Maquiagem" },
    { value: "cosmeticos-naturais", label: "Cosméticos Naturais" },
    { value: "perfumaria", label: "Perfumaria" },
    { value: "depilacao", label: "Depilação" },
    { value: "massoterapia", label: "Massoterapia" },
    { value: "designer-sobrancelhas", label: "Designer de Sobrancelhas" },
    { value: "outro", label: "Outro" },
  ] as const,
  "petshop": [
    { value: "alimentacao-caes", label: "Alimentação para Cães" },
    { value: "alimentacao-gatos", label: "Alimentação para Gatos" },
    { value: "acessorios-caes", label: "Acessórios para Cães" },
    { value: "acessorios-gatos", label: "Acessórios para Gatos" },
    { value: "higiene-beleza", label: "Higiene e Beleza" },
    { value: "brinquedos", label: "Brinquedos" },
    { value: "medicamentos-veterinarios", label: "Medicamentos Veterinários" },
    { value: "servicos-veterinarios", label: "Serviços Veterinários" },
    { value: "pet-exotico", label: "Pet Exótico" },
    { value: "outro", label: "Outro" },
  ] as const,
  "variedades-utilidades": [
    { value: "presentes-souvenirs", label: "Presentes e Souvenirs" },
    { value: "artigos-decoracao", label: "Artigos de Decoração" },
    { value: "utilidades-domesticas", label: "Utilidades Domésticas" },
    { value: "artigos-festa", label: "Artigos para Festa" },
    { value: "papelaria", label: "Papelaria" },
    { value: "brinquedos-gerais", label: "Brinquedos Gerais" },
    { value: "artigos-religiosos", label: "Artigos Religiosos" },
    { value: "artesanato-local", label: "Artesanato Local" },
    { value: "cama-mesa-banho", label: "Cama, Mesa e Banho" },
    { value: "outro", label: "Outro" },
  ] as const,
  "mercados-mercearias": [
    { value: "mercado-mercearia", label: "Mercado / Mercearia" },
  ] as const,
  "restaurantes-lanchonetes": [
    { value: "restaurante-lanchonete", label: "Restaurante / Lanchonete" },
  ] as const,
  "farmacia-saude": [
    { value: "farmacia", label: "Farmácia / Drogaria" },
  ] as const,
  "casa-decoracao": [
    { value: "casa-decoracao", label: "Casa e Decoração" },
  ] as const,
  "eletronicos-tecnologia": [
    { value: "eletronico-tecnologia", label: "Eletrônicos / Tecnologia" },
  ] as const,
  "servicos-locais": [
    { value: "servico-local", label: "Serviço Local" },
  ] as const,
  "outros": [] as const,
};

export const BRAZILIAN_STATES = [
  { value: "AC", label: "Acre" },
  { value: "AL", label: "Alagoas" },
  { value: "AP", label: "Amapá" },
  { value: "AM", label: "Amazonas" },
  { value: "BA", label: "Bahia" },
  { value: "CE", label: "Ceará" },
  { value: "DF", label: "Distrito Federal" },
  { value: "ES", label: "Espírito Santo" },
  { value: "GO", label: "Goiás" },
  { value: "MA", label: "Maranhão" },
  { value: "MT", label: "Mato Grosso" },
  { value: "MS", label: "Mato Grosso do Sul" },
  { value: "MG", label: "Minas Gerais" },
  { value: "PA", label: "Pará" },
  { value: "PB", label: "Paraíba" },
  { value: "PR", label: "Paraná" },
  { value: "PE", label: "Pernambuco" },
  { value: "PI", label: "Piauí" },
  { value: "RJ", label: "Rio de Janeiro" },
  { value: "RN", label: "Rio Grande do Norte" },
  { value: "RS", label: "Rio Grande do Sul" },
  { value: "RO", label: "Rondônia" },
  { value: "RR", label: "Roraima" },
  { value: "SC", label: "Santa Catarina" },
  { value: "SP", label: "São Paulo" },
  { value: "SE", label: "Sergipe" },
  { value: "TO", label: "Tocantins" },
] as const;

export const BADGE_OPTIONS = [
  "Oferta",
  "Promoção",
  "Queima de Estoque",
  "Novidade",
  "Últimas Unidades",
] as const;

export type BadgeOption = (typeof BADGE_OPTIONS)[number];
