export const STORE_SEGMENTS = [
  { value: "moda-calcados-acessorios", label: "Moda, Calçados e Acessórios" },
  { value: "bebidas-adegas-conveniencia", label: "Bebidas, Adegas e Conveniência" },
  { value: "padaria-confeitaria-doces", label: "Padaria, Confeitaria e Doces" },
  { value: "beleza-estetica", label: "Beleza e Estética" },
  { value: "petshop", label: "Pet Shop" },
  { value: "variedades-utilidades", label: "Variedades e Utilidades" },
  { value: "mercados-mercearias", label: "Mercados e Mercearias" },
  { value: "restaurantes-lanchonetes", label: "Restaurantes e Lanchonetes" },
  { value: "farmacia-saude", label: "Farmácia e Saúde" },
  { value: "casa-decoracao", label: "Casa e Decoração" },
  { value: "eletronicos-tecnologia", label: "Eletrônicos e Tecnologia" },
  { value: "servicos-locais", label: "Serviços Locais" },
  { value: "outros", label: "Outros" },
] as const;

export type StoreSegment = (typeof STORE_SEGMENTS)[number]["value"];

export const STORE_SUBSEGMENTS: Record<StoreSegment, readonly { value: string; label: string }[]> = {
  "moda-calcados-acessorios": [
    { value: "moda-feminina", label: "Moda Feminina" },
    { value: "moda-masculina", label: "Moda Masculina" },
    { value: "moda-infantil", label: "Moda Infantil" },
    { value: "moda-intima", label: "Moda Íntima" },
    { value: "moda-fitness", label: "Moda Fitness" },
    { value: "moda-praia", label: "Moda Praia" },
    { value: "calcados", label: "Calçados" },
    { value: "bolsas-acessorios", label: "Bolsas e Acessórios" },
    { value: "bijuterias-semijoias", label: "Bijuterias e Semijoias" },
    { value: "brecho", label: "Brechó" },
    { value: "boutique", label: "Boutique" },
    { value: "outro", label: "Outro" },
  ] as const,
  "bebidas-adegas-conveniencia": [
    { value: "adega", label: "Adega" },
    { value: "loja-de-bebidas", label: "Loja de Bebidas" },
    { value: "distribuidora-de-bebidas", label: "Distribuidora de Bebidas" },
    { value: "emporio-de-bebidas", label: "Empório de Bebidas" },
    { value: "conveniencia", label: "Conveniência" },
    { value: "cervejas-artesanais", label: "Cervejas Artesanais" },
    { value: "vinhos", label: "Vinhos" },
    { value: "destilados", label: "Destilados" },
    { value: "bebidas-geladas", label: "Bebidas Geladas" },
    { value: "outro", label: "Outro" },
  ] as const,
  "padaria-confeitaria-doces": [
    { value: "padaria", label: "Padaria" },
    { value: "panificadora", label: "Panificadora" },
    { value: "confeitaria", label: "Confeitaria" },
    { value: "doceria", label: "Doceria" },
    { value: "bolos-caseiros", label: "Bolos Caseiros" },
    { value: "salgados", label: "Salgados" },
    { value: "cafeteria", label: "Cafeteria" },
    { value: "sorveteria-acaiteria", label: "Sorveteria / Açaíteria" },
    { value: "chocolateria", label: "Chocolateria" },
    { value: "outro", label: "Outro" },
  ] as const,
  "beleza-estetica": [
    { value: "salao-de-beleza", label: "Salão de Beleza" },
    { value: "barbearia", label: "Barbearia" },
    { value: "esmalteria", label: "Esmalteria" },
    { value: "manicure-pedicure", label: "Manicure e Pedicure" },
    { value: "sobrancelhas-cilios", label: "Sobrancelhas e Cílios" },
    { value: "estetica-facial", label: "Estética Facial" },
    { value: "estetica-corporal", label: "Estética Corporal" },
    { value: "depilacao", label: "Depilação" },
    { value: "maquiagem", label: "Maquiagem" },
    { value: "cosmeticos-perfumaria", label: "Cosméticos e Perfumaria" },
    { value: "spa-massagem", label: "Spa e Massagem" },
    { value: "outro", label: "Outro" },
  ] as const,
  "petshop": [
    { value: "pet-shop", label: "Pet Shop" },
    { value: "banho-e-tosa", label: "Banho e Tosa" },
    { value: "racoes", label: "Rações" },
    { value: "acessorios-pet", label: "Acessórios Pet" },
    { value: "produtos-veterinarios", label: "Produtos Veterinários" },
    { value: "aquarismo", label: "Aquarismo" },
    { value: "aves-peixes", label: "Aves e Peixes" },
    { value: "pet-premium", label: "Pet Premium" },
    { value: "servicos-pet", label: "Serviços Pet" },
    { value: "outro", label: "Outro" },
  ] as const,
  "variedades-utilidades": [
    { value: "loja-de-variedades", label: "Loja de Variedades" },
    { value: "bazar", label: "Bazar" },
    { value: "loja-popular", label: "Loja Popular" },
    { value: "utilidades-domesticas", label: "Utilidades Domésticas" },
    { value: "papelaria", label: "Papelaria" },
    { value: "brinquedos", label: "Brinquedos" },
    { value: "presentes", label: "Presentes" },
    { value: "armarinhos", label: "Armarinhos" },
    { value: "embalagens", label: "Embalagens" },
    { value: "artigos-de-festa", label: "Artigos de Festa" },
    { value: "outro", label: "Outro" },
  ] as const,
  "mercados-mercearias": [
    { value: "mercados-mercearias", label: "Mercados e Mercearias" },
  ] as const,
  "restaurantes-lanchonetes": [
    { value: "restaurantes-lanchonetes", label: "Restaurantes e Lanchonetes" },
  ] as const,
  "farmacia-saude": [
    { value: "farmacia-saude", label: "Farmácia e Saúde" },
  ] as const,
  "casa-decoracao": [
    { value: "casa-decoracao", label: "Casa e Decoração" },
  ] as const,
  "eletronicos-tecnologia": [
    { value: "eletronicos-tecnologia", label: "Eletrônicos e Tecnologia" },
  ] as const,
  "servicos-locais": [
    { value: "servicos-locais", label: "Serviços Locais" },
  ] as const,
  "outros": [
    { value: "outros", label: "Outros" },
  ] as const,
};

export const BRAZILIAN_STATES = [
  { value: "AC", label: "Acre" },
  { value: "AL", label: "Alagoas" },
  { value: "AP", label: "Amapá" },
  { value: "AM", label: "Amazonas" },
  { value: "BA", label: "Bahia" },
  { value: "CE", label: "Ceará" },
  { value: "DF", label: "Distrito Federal" },
  { value: "ES", label: "Espírito Santo" },
  { value: "GO", label: "Goiás" },
  { value: "MA", label: "Maranhão" },
  { value: "MT", label: "Mato Grosso" },
  { value: "MS", label: "Mato Grosso do Sul" },
  { value: "MG", label: "Minas Gerais" },
  { value: "PA", label: "Pará" },
  { value: "PB", label: "Paraíba" },
  { value: "PR", label: "Paraná" },
  { value: "PE", label: "Pernambuco" },
  { value: "PI", label: "Piauí" },
  { value: "RJ", label: "Rio de Janeiro" },
  { value: "RN", label: "Rio Grande do Norte" },
  { value: "RS", label: "Rio Grande do Sul" },
  { value: "RO", label: "Rondônia" },
  { value: "RR", label: "Roraima" },
  { value: "SC", label: "Santa Catarina" },
  { value: "SP", label: "São Paulo" },
  { value: "SE", label: "Sergipe" },
  { value: "TO", label: "Tocantins" },
] as const;

export const BADGE_OPTIONS = [
  "Oferta",
  "Promoção",
  "Queima de Estoque",
  "Novidade",
  "Últimas Unidades",
] as const;

export type BadgeOption = (typeof BADGE_OPTIONS)[number];
