import { z } from "zod";
import type { CampaignIntent } from "@/lib/campaign/types";

// ─── Campaign Generation Input ─────────────────────────────────────────────
// Input received from the campaign form. `brandColor` is the RESOLVED hex
// color after resolveStoreIdentity fallback, NOT raw store brand_color (which may be null).

export const CampaignGenerationInputSchema = z.object({
  productName: z.string().min(1, "Nome do produto é obrigatório"),
  originalPriceCents: z
    .number()
    .int("Preço original deve ser um número inteiro")
    .nonnegative()
    .optional(),
  discountedPriceCents: z
    .number()
    .int("Preço com desconto deve ser um número inteiro")
    .positive("Preço com desconto deve ser positivo"),
  campaignIntent: z
    .enum(["offer", "spotlight", "exclusive"])
    .optional()
    .default("offer"),
  description: z.string().optional(),
  badge: z.string().optional(),
  storeName: z.string().min(1, "Nome da loja é obrigatório"),
  storeSegment: z.string().min(1, "Segmento da loja é obrigatório"),
  brandColor: z
    .string()
    .regex(/^#[0-9a-fA-F]{6}$/, "Deve ser uma cor hexadecimal válida"),
  city: z.string().optional(),
  state: z
    .string()
    .length(2, "Estado deve ter exatamente 2 caracteres")
    .optional(),
});

export type CampaignGenerationInput = z.infer<typeof CampaignGenerationInputSchema>;

// ─── Campaign Spec ─────────────────────────────────────────────────────────
// Output generated by the AI provider and validated before returning.

export const CampaignSpecSchema = z.object({
  commercial_copy: z.object({
    title: z.string().min(1, "Título é obrigatório"),
    subtitle: z.string().min(1, "Subtítulo é obrigatório"),
    hook: z.string().min(1, "Chamada é obrigatória"),
    cta: z.string().min(1, "CTA é obrigatório"),
  }),
  offer: z.object({
    product_name: z.string().min(1, "Nome do produto é obrigatório"),
    original_price_display: z.string().nullable(),
    discounted_price_display: z.string().min(1, "Preço com desconto é obrigatório"),
    badge_text: z.string().min(1, "Texto do badge é obrigatório"),
  }),
  visual_parameters: z.object({
    layout_preset: z.string().min(1, "Layout é obrigatório"),
    composition_type: z.string().min(1, "Tipo de composição é obrigatório"),
    hierarchy_focus: z.string().min(1, "Foco de hierarquia é obrigatório"),
    palette_accent: z.string().min(1, "Cor de destaque é obrigatória"),
    badge_style: z.string().min(1, "Estilo do badge é obrigatório"),
    background_style: z.string().min(1, "Estilo de fundo é obrigatório"),
  }),
  generation_metadata: z.object({
    provider: z.string().min(1, "Provedor é obrigatório"),
    model: z.string().min(1, "Modelo é obrigatório"),
    generated_at: z
      .string()
      .datetime({ message: "Deve ser uma data ISO 8601" }),
  }),
});

export type CampaignSpec = z.infer<typeof CampaignSpecSchema>;

// ─── Error Response ────────────────────────────────────────────────────────
// Structured error payload returned to the client.

export const ErrorResponseSchema = z.object({
  error: z.object({
    message: z.string(),
  }),
});

export type ErrorResponse = z.infer<typeof ErrorResponseSchema>;
