import { requireAdmin } from "@/lib/admin/require-admin";
import { supabaseAdmin } from "@/lib/supabase/server";

export const dynamic = "force-dynamic";

export default async function DataSubjectRequestsPage() {
  try { await requireAdmin(); } catch { return <p className="text-destructive">Acesso negado.</p>; }
  const { data, error } = await supabaseAdmin.from("data_subject_requests").select("*").order("requested_at", { ascending: false });
  if (error) return <p className="text-destructive">Erro ao carregar pedidos: {error.message}</p>;
  return <div><h1 className="mb-2 font-heading text-2xl font-bold">Pedidos de titular</h1><p className="mb-6 text-sm text-text-secondary">Direitos tratados pelo suporte com protocolo. Não há autosserviço.</p><form method="post" action="/api/admin/data-subject-requests" className="mb-8 grid gap-2 rounded-lg border p-4"><input name="_method" value="POST" readOnly hidden /><input name="action" value="register" readOnly hidden /><select name="type" required className="rounded border bg-bg-surface p-2"><option value="access">Acesso</option><option value="export">Exportação</option><option value="correction">Correção</option><option value="deletion">Exclusão</option><option value="closure">Encerramento</option></select><input name="contact" required placeholder="Contato" className="rounded border bg-bg-surface p-2" /><textarea name="details" required placeholder="Detalhes mínimos do pedido" className="rounded border bg-bg-surface p-2" /><button className="rounded bg-accent-blue px-4 py-2 text-white" type="submit">Registrar pedido</button></form><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-xs uppercase text-text-muted"><th className="px-2 py-3">Protocolo</th><th className="px-2 py-3">Tipo</th><th className="px-2 py-3">Status</th><th className="px-2 py-3">Contato</th><th className="px-2 py-3">Ações</th></tr></thead><tbody>{(data ?? []).map((row) => <tr className="border-b" key={row.id}><td className="px-2 py-3 font-mono">{row.protocol}</td><td className="px-2 py-3">{row.type}</td><td className="px-2 py-3">{row.status}</td><td className="px-2 py-3">{row.contact}</td><td className="px-2 py-3"><div className="flex gap-2">{row.status === "received" && <form method="post" action="/api/admin/data-subject-requests"><input name="action" value="transition" readOnly hidden /><input name="id" value={row.id} readOnly hidden /><input name="nextStatus" value="in_progress" readOnly hidden /><button className="underline" type="submit">Iniciar</button></form>}{row.status === "received" && <form method="post" action="/api/admin/data-subject-requests"><input name="action" value="transition" readOnly hidden /><input name="id" value={row.id} readOnly hidden /><input name="nextStatus" value="cancelled" readOnly hidden /><button className="underline text-accent-red" type="submit">Cancelar</button></form>}{row.status === "in_progress" && <form method="post" action="/api/admin/data-subject-requests"><input name="action" value="transition" readOnly hidden /><input name="id" value={row.id} readOnly hidden /><input name="nextStatus" value="completed" readOnly hidden /><button className="underline" type="submit">Concluir</button></form>}</div></td></tr>)}</tbody></table></div></div>;
}
