-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.stores (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL CHECK (char_length(name) >= 2 AND char_length(name) <= 60),
  segment text NOT NULL CHECK (segment = ANY (ARRAY['moda-calcados-acessorios'::text, 'bebidas-adegas-conveniencia'::text, 'padaria-confeitaria-doces'::text, 'beleza-estetica'::text, 'petshop'::text, 'variedades-utilidades'::text, 'mercados-mercearias'::text, 'restaurantes-lanchonetes'::text, 'farmacia-saude'::text, 'casa-decoracao'::text, 'eletronicos-tecnologia'::text, 'servicos-locais'::text, 'outros'::text])),
  city text,
  state text,
  brand_color text,
  logo_url text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  subsegment text,
  tone_of_voice text,
  positioning text,
  short_description text,
  slogan text,
  logo_status text CHECK (logo_status IS NULL OR (logo_status = ANY (ARRAY['uploaded'::text, 'generated'::text, 'explicit_none'::text, 'failed'::text, 'exhausted'::text]))),
  visual_signature_attempts integer NOT NULL DEFAULT 0,
  identity_state text NOT NULL DEFAULT 'text_only'::text CHECK (identity_state = ANY (ARRAY['text_only'::text, 'logo'::text, 'visual_signature'::text])),
  previous_identity_snapshot jsonb,
  text_only_origin text NOT NULL DEFAULT 'implicit'::text CHECK (text_only_origin = ANY (ARRAY['implicit'::text, 'explicit'::text])),
  manual_color_override boolean NOT NULL DEFAULT false,
  CONSTRAINT stores_pkey PRIMARY KEY (id)
);
CREATE TABLE public.store_visual_signatures (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  store_id uuid NOT NULL,
  storage_path text NOT NULL,
  asset_url text NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['ai_generated'::text, 'automatic_generated'::text, 'fallback_typographic'::text])),
  status text NOT NULL CHECK (status = ANY (ARRAY['draft'::text, 'active'::text, 'archived'::text])),
  generation_mode text CHECK (generation_mode IS NULL OR (generation_mode = ANY (ARRAY['user_choice'::text, 'automatic'::text, 'fallback'::text]))),
  prompt text,
  metadata jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT store_visual_signatures_pkey PRIMARY KEY (id),
  CONSTRAINT store_visual_signatures_store_id_fkey FOREIGN KEY (store_id) REFERENCES public.stores(id)
);
CREATE TABLE public.store_brand_assets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  store_id uuid NOT NULL,
  asset_type text NOT NULL DEFAULT 'logo'::text CHECK (asset_type = 'logo'::text),
  variant_type text NOT NULL CHECK (variant_type = ANY (ARRAY['original'::text, 'normalized'::text, 'on_light'::text, 'on_dark'::text, 'square_safe'::text, 'horizontal_safe'::text])),
  source text NOT NULL CHECK (source = ANY (ARRAY['user_upload'::text, 'system_generated'::text])),
  parent_asset_id uuid,
  storage_path text,
  mime_type text NOT NULL,
  width integer NOT NULL,
  height integer NOT NULL,
  size_bytes integer NOT NULL,
  checksum text NOT NULL,
  version integer NOT NULL,
  status text NOT NULL CHECK (status = ANY (ARRAY['active'::text, 'archived'::text, 'failed'::text])),
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT store_brand_assets_pkey PRIMARY KEY (id),
  CONSTRAINT store_brand_assets_store_id_fkey FOREIGN KEY (store_id) REFERENCES public.stores(id),
  CONSTRAINT store_brand_assets_parent_asset_id_fkey FOREIGN KEY (parent_asset_id) REFERENCES public.store_brand_assets(id)
);
CREATE TABLE public.store_brand_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  store_id uuid NOT NULL,
  source text NOT NULL DEFAULT 'logo_analysis'::text CHECK (source = ANY (ARRAY['logo_analysis'::text, 'without_logo'::text, 'text_only'::text])),
  active_logo_asset_id uuid,
  logo_colors_detected jsonb DEFAULT '[]'::jsonb,
  brand_colors_chosen jsonb DEFAULT '[]'::jsonb,
  safe_color_tokens jsonb DEFAULT '{}'::jsonb,
  visual_style text,
  visual_tone text,
  typography_direction text,
  brand_personality text,
  campaign_guidelines text,
  campaign_brief text,
  confidence_score real,
  metadata jsonb DEFAULT '{}'::jsonb,
  version integer NOT NULL DEFAULT 1,
  status text NOT NULL CHECK (status = ANY (ARRAY['processing'::text, 'synced'::text, 'outdated'::text, 'failed'::text, 'archived'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  visual_signature_id uuid,
  inferred_primary_color text,
  inferred_accent_color text,
  identity_art_director_output jsonb DEFAULT '{}'::jsonb,
  manual_color_override jsonb NOT NULL DEFAULT '{"enabled": false}'::jsonb,
  CONSTRAINT store_brand_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT store_brand_profiles_store_id_fkey FOREIGN KEY (store_id) REFERENCES public.stores(id),
  CONSTRAINT store_brand_profiles_active_logo_asset_id_fkey FOREIGN KEY (active_logo_asset_id) REFERENCES public.store_brand_assets(id),
  CONSTRAINT store_brand_profiles_visual_signature_id_fkey FOREIGN KEY (visual_signature_id) REFERENCES public.store_visual_signatures(id)
);
CREATE TABLE public.generation_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  store_id uuid NOT NULL,
  generation_type text NOT NULL CHECK (generation_type = ANY (ARRAY['visual_signature'::text, 'brand_profile_without_logo'::text, 'brand_profile_with_logo'::text])),
  provider text,
  model text,
  duration_ms integer,
  estimated_cost_usd real,
  attempt_number integer NOT NULL DEFAULT 1,
  status text NOT NULL CHECK (status = ANY (ARRAY['success'::text, 'failed'::text, 'rejected'::text, 'timeout'::text])),
  error_type text,
  prompt_version text,
  approved boolean,
  rejected boolean,
  asset_generated boolean,
  asset_id uuid,
  has_logo boolean,
  has_generated_signature boolean,
  has_brand_profile boolean,
  input_data_hash text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT generation_events_pkey PRIMARY KEY (id),
  CONSTRAINT generation_events_store_id_fkey FOREIGN KEY (store_id) REFERENCES public.stores(id)
);